language: cpp
dist: trusty
compiler:
  - clang
  - gcc
#before_install: sudo add-apt-repository --yes ppa:kalakris/cmake && sudo apt-get update -qq && sudo apt-get install cmake
script: mkdir -p build && cd build && ../configure --enable-debug && make